version: "3.4"

name: weather
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'alinares'
      MYSQL_PASSWORD: 'Alinares94$$'
      MYSQL_ROOT_PASSWORD: 'Alinares94$$'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
  weatherapi:
     environment:
       - ASPNETCORE_ENVIRONMENT=Release
     depends_on:
       - db
     image: weather-api
     build:
       context: .
     ports:
       - "8080:80"
  weatherapp:
     depends_on:
       - weatherapi
     image: weather-app
     ports:
       - "8081:80"
volumes:
  mysql_data:
    driver: local
networks:
  default:
    name: weatherNet
